apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # use base64 encoded string for username and password.
  mongo-user: <username without quotes>
  mongo-password: <password without quotes>
